#define MCLK_FREQUENCY      48000000
#define SMCLK_FREQUENCY     24000000
#define NUMBER_OF_SAMPLES       128
#define CONVERSIONS_PER_SAMPLE  8
#define ADC_TASKS               NUMBER_OF_SAMPLES+2
 
uint32_t dataSet_01[NUMBER_OF_SAMPLES][CONVERSIONS_PER_SAMPLE];
uint32_t dataSet_02[NUMBER_OF_SAMPLES][CONVERSIONS_PER_SAMPLE];
const uint8_t forceP1B2ISR = 0x04;  // P1.2 is high
const uint8_t forceP1B3ISR = 0x08;  // P1.3 is high
bool dataSet0Ready;
 
#if defined(__TI_COMPILER_VERSION__)
#pragma DATA_ALIGN(MSP_EXP432P401RLP_DMAControlTable, 1024)
#elif defined(__IAR_SYSTEMS_ICC__)
#pragma data_alignment=1024
#elif defined(__GNUC__)
__attribute__ ((aligned (1024)))
#elif defined(__CC_ARM)
__align(1024)
#endif
static DMA_ControlTable MSP_EXP432P401RLP_DMAControlTable[16];  // 8 primary and 8 alternate
DMA_ControlTable pingTask,pongTask;
 
const DMA_ControlTable AdcDmaSeq_01[ADC_TASKS] =
{
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[0][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[1][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[2][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[3][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[4][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[5][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[6][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[7][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[8][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[9][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[10][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[11][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[12][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[13][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[14][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[15][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[16][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[17][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[18][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[19][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[20][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[21][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[22][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[23][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[24][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[25][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[26][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[27][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[28][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[29][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[30][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[31][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[32][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[33][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[34][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[35][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[36][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[37][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[38][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[39][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[40][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[41][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[42][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[43][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[44][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[45][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[46][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[47][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[48][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[49][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[50][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[51][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[52][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[53][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[54][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[55][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[56][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[57][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[58][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[59][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[60][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[61][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[62][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[63][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[64][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[65][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[66][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[67][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[68][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[69][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[70][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[71][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[72][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[73][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[74][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[75][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[76][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[77][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[78][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[79][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[80][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[81][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[82][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[83][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[84][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[85][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[86][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[87][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[88][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[89][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[90][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[91][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[92][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[93][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[94][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[95][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[96][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[97][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[98][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[99][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[100][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[101][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[102][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[103][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[104][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[105][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[106][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[107][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[108][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[109][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[110][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[111][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[112][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[113][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[114][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[115][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[116][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[117][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[118][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[119][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[120][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[121][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[122][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[123][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[124][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[125][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[126][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[127][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),

DMA_TaskStructEntry(1, UDMA_SIZE_8,
            UDMA_SRC_INC_8, (void *)&forceP1B2ISR,
            UDMA_DST_INC_8, (void *)&P1->OUT,
            UDMA_ARB_1, UDMA_MODE_MEM_SCATTER_GATHER),
DMA_TaskStructEntry(4, UDMA_SIZE_32,
            UDMA_SRC_INC_32, (void *)&pongTask,
            UDMA_DST_INC_32, (void *)&MSP_EXP432P401RLP_DMAControlTable[7],
            UDMA_ARB_4, UDMA_MODE_MEM_SCATTER_GATHER)
};

const DMA_ControlTable AdcDmaSeq_02[ADC_TASKS] =
{
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[0][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[1][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[2][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[3][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[4][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[5][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[6][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[7][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[8][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[9][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[10][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[11][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[12][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[13][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[14][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[15][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[16][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[17][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[18][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[19][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[20][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[21][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[22][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[23][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[24][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[25][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[26][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[27][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[28][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[29][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[30][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[31][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[32][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[33][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[34][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[35][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[36][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[37][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[38][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[39][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[40][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[41][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[42][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[43][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[44][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[45][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[46][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[47][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[48][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[49][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[50][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[51][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[52][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[53][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[54][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[55][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[56][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[57][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[58][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[59][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[60][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[61][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[62][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[63][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[64][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[65][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[66][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[67][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[68][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[69][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[70][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[71][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[72][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[73][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[74][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[75][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[76][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[77][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[78][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[79][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[80][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[81][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[82][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[83][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[84][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[85][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[86][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[87][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[88][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[89][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[90][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[91][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[92][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[93][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[94][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[95][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[96][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[97][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[98][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[99][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[100][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[101][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[102][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[103][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[104][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[105][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[106][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[107][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[108][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[109][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[110][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[111][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[112][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[113][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[114][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[115][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[116][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[117][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[118][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[119][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[120][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[121][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[122][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[123][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[124][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[125][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[126][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(8, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[127][0],
        UDMA_ARB_1, UDMA_MODE_PER_SCATTER_GATHER),

DMA_TaskStructEntry(1, UDMA_SIZE_8,
            UDMA_SRC_INC_8, (void *)&forceP1B2ISR,
            UDMA_DST_INC_8, (void *)&P1->OUT,
            UDMA_ARB_1, UDMA_MODE_MEM_SCATTER_GATHER),
DMA_TaskStructEntry(4, UDMA_SIZE_32,
            UDMA_SRC_INC_32, (void *)&pingTask,
            UDMA_DST_INC_32, (void *)&MSP_EXP432P401RLP_DMAControlTable[7],
            UDMA_ARB_4, UDMA_MODE_MEM_SCATTER_GATHER)
};
