#define MCLK_FREQUENCY      48000000
#define SMCLK_FREQUENCY     24000000
#define NUMBER_OF_SAMPLES       512
#define CONVERSIONS_PER_SAMPLE  8
#define ADC_TASKS               (NUMBER_OF_SAMPLES/4)+2
 
uint32_t dataSet_01[NUMBER_OF_SAMPLES][CONVERSIONS_PER_SAMPLE];
uint32_t dataSet_02[NUMBER_OF_SAMPLES][CONVERSIONS_PER_SAMPLE];
const uint8_t forceP1B2ISR = 0x04;  // P1.2 is high
const uint8_t forceP1B3ISR = 0x08;  // P1.3 is high
bool dataSet0Ready;
 
#if defined(__TI_COMPILER_VERSION__)
#pragma DATA_ALIGN(MSP_EXP432P401RLP_DMAControlTable, 1024)
#elif defined(__IAR_SYSTEMS_ICC__)
#pragma data_alignment=1024
#elif defined(__GNUC__)
__attribute__ ((aligned (1024)))
#elif defined(__CC_ARM)
__align(1024)
#endif
static DMA_ControlTable MSP_EXP432P401RLP_DMAControlTable[16];  // 8 primary and 8 alternate
DMA_ControlTable pingTask,pongTask;
 
const DMA_ControlTable AdcDmaSeq_01[ADC_TASKS] =
{
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[0][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[4][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[8][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[12][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[16][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[20][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[24][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[28][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[32][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[36][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[40][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[44][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[48][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[52][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[56][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[60][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[64][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[68][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[72][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[76][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[80][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[84][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[88][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[92][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[96][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[100][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[104][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[108][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[112][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[116][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[120][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[124][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[128][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[132][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[136][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[140][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[144][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[148][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[152][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[156][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[160][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[164][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[168][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[172][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[176][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[180][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[184][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[188][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[192][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[196][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[200][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[204][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[208][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[212][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[216][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[220][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[224][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[228][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[232][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[236][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[240][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[244][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[248][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[252][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[256][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[260][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[264][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[268][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[272][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[276][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[280][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[284][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[288][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[292][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[296][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[300][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[304][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[308][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[312][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[316][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[320][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[324][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[328][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[332][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[336][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[340][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[344][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[348][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[352][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[356][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[360][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[364][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[368][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[372][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[376][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[380][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[384][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[388][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[392][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[396][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[400][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[404][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[408][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[412][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[416][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[420][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[424][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[428][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[432][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[436][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[440][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[444][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[448][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[452][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[456][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[460][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[464][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[468][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[472][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[476][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[480][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[484][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[488][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[492][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[496][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[500][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[504][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_01[508][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),

DMA_TaskStructEntry(1, UDMA_SIZE_8,
            UDMA_SRC_INC_8, (void *)&forceP1B2ISR,
            UDMA_DST_INC_8, (void *)&P1->OUT,
            UDMA_ARB_1, UDMA_MODE_MEM_SCATTER_GATHER),
DMA_TaskStructEntry(4, UDMA_SIZE_32,
            UDMA_SRC_INC_32, (void *)&pongTask,
            UDMA_DST_INC_32, (void *)&MSP_EXP432P401RLP_DMAControlTable[7],
            UDMA_ARB_4, UDMA_MODE_MEM_SCATTER_GATHER)
};

const DMA_ControlTable AdcDmaSeq_02[ADC_TASKS] =
{
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[0][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[4][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[8][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[12][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[16][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[20][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[24][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[28][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[32][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[36][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[40][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[44][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[48][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[52][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[56][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[60][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[64][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[68][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[72][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[76][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[80][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[84][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[88][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[92][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[96][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[100][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[104][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[108][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[112][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[116][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[120][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[124][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[128][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[132][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[136][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[140][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[144][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[148][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[152][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[156][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[160][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[164][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[168][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[172][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[176][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[180][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[184][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[188][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[192][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[196][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[200][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[204][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[208][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[212][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[216][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[220][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[224][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[228][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[232][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[236][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[240][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[244][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[248][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[252][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[256][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[260][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[264][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[268][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[272][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[276][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[280][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[284][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[288][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[292][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[296][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[300][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[304][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[308][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[312][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[316][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[320][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[324][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[328][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[332][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[336][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[340][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[344][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[348][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[352][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[356][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[360][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[364][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[368][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[372][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[376][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[380][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[384][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[388][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[392][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[396][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[400][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[404][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[408][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[412][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[416][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[420][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[424][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[428][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[432][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[436][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[440][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[444][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[448][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[452][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[456][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[460][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[464][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[468][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[472][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[476][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[480][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[484][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[488][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[492][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[496][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[500][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[504][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),
DMA_TaskStructEntry(32, UDMA_SIZE_32,
        UDMA_SRC_INC_32,(void*)&ADC14->MEM[0],
        UDMA_DST_INC_32, &dataSet_02[508][0],
        UDMA_ARB_32, UDMA_MODE_PER_SCATTER_GATHER),

DMA_TaskStructEntry(1, UDMA_SIZE_8,
            UDMA_SRC_INC_8, (void *)&forceP1B2ISR,
            UDMA_DST_INC_8, (void *)&P1->OUT,
            UDMA_ARB_1, UDMA_MODE_MEM_SCATTER_GATHER),
DMA_TaskStructEntry(4, UDMA_SIZE_32,
            UDMA_SRC_INC_32, (void *)&pingTask,
            UDMA_DST_INC_32, (void *)&MSP_EXP432P401RLP_DMAControlTable[7],
            UDMA_ARB_4, UDMA_MODE_MEM_SCATTER_GATHER)
};
